name: "Cut Release for JSON2GBNF (Javascript)"

on:
  push:
    tags:
      - "js/json2gbnf-v*"

jobs:
  release:
    name: "Cut Release for JSON2GBNF (Javascript)"
    uses: ./.github/workflows/js-shared-release.yaml

    with:
      package: "./packages/json2gbnf/javascript"
      files: |
        packages/json2gbnf/javascript/json2gbnf-*.tgz
